---
- name: creating tags and implementing
  hosts: all
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
      tags: tree-installtion    #tag name can be anything
    - name: create user
      user:
        name: Ravi
        password: 1234
      tags: user-creation           #tagged
    - name: copy files                  #untagged
      copy:
        src: /etc/passwd
        dest: /tmp